### ISSUE TITLE
Edit window too small

### ISSUE THREAD

**Issue by milossramek** [isaul32/ckeditor5-math#10]
LaTeX formulas can get really large and often require multiple lines. However, the editing field in the popup widget is very small. Would it be possible to make it multiline and to add it a possibility to change the popup size?
Thanks!

**Comment by isaul32** [comment]
You can try do some CSS rules for .ck-math-form in your styles. I can also look if I can add config option for that.

**Comment by milossramek** [comment]
I am sorry, I do not know what to do. I've found .ck-math-form in theme/mathform.css, but I have no idea what to set there. :(

**Comment by isaul32** [comment]
E.g. this doubles the width of input.

```css
.ck-math-form input.ck.ck-input.ck-input-text {
  min-width: 36em; /* default is 18em */
}
```

Multiline support requires more work. Custom labeled textarea view need to be implemeted for that. I try implement it at some point.
